comments: true
hide:
  - feedback
authors:
  katterfelto:
    name: Dave Moor
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/katterfelto